// path: src/components/reports/ExecutiveBriefingModal.tsx
import { useState, useEffect } from "react";
import { createPortal } from "react-dom";
import { useNavigate } from "react-router-dom";
import {
  Sparkles,
  TrendingUp,
  CheckCircle2,
  Building2,
  Copy,
  Check,
  Printer,
  RefreshCw,
  Users,
  Clock,
  ShieldAlert,
  Lightbulb,
  ArrowUpRight,
  X,
} from "lucide-react";
import { Button } from "@/components/ui/Button";
import { formatCurrencyINR } from "@/lib/format";
import type { ExecutiveBriefingResult } from "@/types";

function getConcernRoute(area: string, title: string): string | null {
  const text = `${area} ${title}`.toLowerCase();
  if (text.includes("ticket") || text.includes("helpdesk") || text.includes("support")) {
    return "/app/tickets";
  }
  if (text.includes("recruit") || text.includes("hiring") || text.includes("applicant") || text.includes("candidate")) {
    return "/app/recruitment";
  }
  if (text.includes("attend") || text.includes("punctual") || text.includes("absent")) {
    return "/app/attendance";
  }
  if (text.includes("payroll") || text.includes("lop") || text.includes("salary") || text.includes("deduction")) {
    return "/app/payroll";
  }
  if (text.includes("leave")) {
    return "/app/leave";
  }
  if (text.includes("performance") || text.includes("review") || text.includes("rating")) {
    return "/app/performance";
  }
  if (text.includes("retention") || text.includes("turnover") || text.includes("attrition") || text.includes("headcount")) {
    return "/app/employees";
  }
  return null;
}

function getActionLabel(area: string, title: string): string {
  const text = `${area} ${title}`.toLowerCase();
  if (text.includes("ticket") || text.includes("helpdesk") || text.includes("support")) {
    return "Open Tickets";
  }
  if (text.includes("recruit") || text.includes("hiring")) {
    return "Open Recruitment";
  }
  if (text.includes("attend")) {
    return "Open Attendance";
  }
  if (text.includes("payroll")) {
    return "Open Payroll";
  }
  if (text.includes("leave")) {
    return "Open Leaves";
  }
  if (text.includes("performance")) {
    return "Open Performance";
  }
  if (text.includes("retention") || text.includes("turnover") || text.includes("attrition")) {
    return "Open Directory";
  }
  return "Investigate";
}

function getRecommendationRoute(category: string): string | null {
  switch (category) {
    case "OPERATIONS":
      return "/app/tickets";
    case "TALENT":
      return "/app/recruitment";
    case "ATTENDANCE":
      return "/app/attendance";
    case "COST":
      return "/app/payroll";
    default:
      return null;
  }
}

interface ExecutiveBriefingModalProps {
  isOpen: boolean;
  onClose: () => void;
  data: ExecutiveBriefingResult | null;
  isLoading: boolean;
  onRefresh: () => void;
}

export function ExecutiveBriefingModal({
  isOpen,
  onClose,
  data,
  isLoading,
  onRefresh,
}: ExecutiveBriefingModalProps) {
  const [copied, setCopied] = useState(false);
  const navigate = useNavigate();

  useEffect(() => {
    if (!isOpen) return;
    const handleKeyDown = (event: KeyboardEvent) => {
      if (event.key === "Escape") {
        onClose();
      }
    };
    document.addEventListener("keydown", handleKeyDown);
    const prevOverflow = document.body.style.overflow;
    document.body.style.overflow = "hidden";
    return () => {
      document.removeEventListener("keydown", handleKeyDown);
      document.body.style.overflow = prevOverflow;
    };
  }, [isOpen, onClose]);

  if (!isOpen) return null;

  const handleCopyMarkdown = () => {
    if (!data) return;

    const highlightsMd = data.keyHighlights.map((h) => `- ${h}`).join("\n");
    const concernsMd = data.criticalConcerns
      .map(
        (c) =>
          `- **[${c.severity}] ${c.title}** (${c.area}): ${c.description}${
            c.metric ? ` [Metric: ${c.metric}]` : ""
          }`,
      )
      .join("\n");
    const recsMd = data.strategicRecommendations
      .map(
        (r, i) =>
          `${i + 1}. **[${r.priority}] ${r.category}**: ${r.action}\n   *Expected Impact:* ${r.expectedImpact}`,
      )
      .join("\n");

    const fullMarkdown = `# Executive HR Briefing (${data.periodLabel})
**Health Score:** ${data.healthScore}/100

## Executive Summary
${data.executiveSummary || data.headline}

## Key Highlights
${highlightsMd}

## Critical Concerns
${concernsMd}

## Strategic Recommendations
${recsMd}

---
*Generated by Aadhyaraj HRMS AI Strategy Engine on ${new Date(
      data.generatedAt,
    ).toLocaleDateString("en-IN")} (${data.source === "llm" ? "LLM Powered" : "Rule Engine"})*`;

    navigator.clipboard.writeText(fullMarkdown).then(() => {
      setCopied(true);
      setTimeout(() => setCopied(false), 2500);
    });
  };

  const handlePrint = () => {
    window.print();
  };

  const getHealthBadge = (score: number) => {
    if (score >= 85) {
      return {
        label: "Strong Health",
        bg: "bg-emerald-50 text-emerald-700 border-emerald-200",
        ring: "text-emerald-500",
      };
    }
    if (score >= 70) {
      return {
        label: "Moderate Stability",
        bg: "bg-amber-50 text-amber-700 border-amber-200",
        ring: "text-amber-500",
      };
    }
    return {
      label: "Needs Attention",
      bg: "bg-rose-50 text-rose-700 border-rose-200",
      ring: "text-rose-500",
    };
  };

  const badge = data ? getHealthBadge(data.healthScore) : null;

  return createPortal(
    <div
      className="fixed inset-0 z-[99999] flex h-[100dvh] w-screen items-center justify-center p-4 sm:p-6 print:p-0"
      role="dialog"
      aria-modal="true"
    >
      <div
        className="fixed inset-0 bg-black/50 backdrop-blur-sm print:hidden"
        onClick={onClose}
      />
      <div
        className="relative z-10 flex w-full max-w-4xl flex-col overflow-hidden rounded-3xl bg-white shadow-2xl border border-line max-h-[calc(100dvh-32px)] sm:max-h-[calc(100dvh-48px)] print:max-h-none print:shadow-none print:border-none print:w-full print:max-w-none"
        onClick={(e) => e.stopPropagation()}
      >
        {/* Header */}
        <div className="flex items-start justify-between border-b border-line px-6 py-4.5 bg-white shrink-0">
          <div>
            <div className="flex items-center gap-2 mb-1">
              <span className="inline-flex items-center gap-1.5 px-2.5 py-0.5 rounded-full text-[11px] font-semibold tracking-wide uppercase bg-brand-50 text-brand-700 border border-brand-200">
                <Sparkles size={12} className="text-brand-600 animate-pulse" />
                AI Executive Intelligence
              </span>
              {data && (
                <span className="text-[12px] text-ink-faint font-medium">
                  {data.periodLabel}
                </span>
              )}
            </div>
            <h2 className="text-xl font-display font-semibold text-ink">
              Executive HR Briefing & Strategy Report
            </h2>
          </div>
          <div className="flex items-center gap-2">
            <Button
              variant="outline"
              size="sm"
              onClick={onRefresh}
              disabled={isLoading}
              className="h-8 gap-1.5 text-[12px]"
            >
              <RefreshCw size={13} className={isLoading ? "animate-spin" : ""} />
              Re-analyze
            </Button>
            <button
              onClick={onClose}
              className="p-1.5 rounded-lg text-ink-faint hover:text-ink hover:bg-black/5 transition-colors print:hidden"
              aria-label="Close modal"
            >
              <X size={18} />
            </button>
          </div>
        </div>

        {/* Content Body */}
        <div className="overflow-y-auto px-6 py-5 space-y-6 bg-canvas/40">
          {isLoading ? (
            <div className="py-20 flex flex-col items-center justify-center text-center">
              <div className="h-12 w-12 rounded-full border-4 border-brand-200 border-t-brand-600 animate-spin mb-4" />
              <h3 className="text-base font-medium text-ink">
                Generating Executive Briefing...
              </h3>
              <p className="text-sm text-ink-faint max-w-sm mt-1">
                Synthesizing workforce metrics, attendance patterns, payroll
                commitments, and operational tickets.
              </p>
            </div>
          ) : !data ? (
            <div className="py-16 text-center text-ink-faint">
              No briefing data available. Click Re-analyze to generate.
            </div>
          ) : (
            <>
              {/* Executive Health Score & Metric Bar */}
              <div className="rounded-2xl border border-line bg-white p-5 shadow-xs">
                <div className="grid grid-cols-1 md:grid-cols-4 gap-4 items-center">
                  {/* Score */}
                  <div className="flex items-center gap-4 md:border-r md:border-line md:pr-4">
                    <div className="relative flex items-center justify-center h-16 w-16 rounded-full bg-brand-50 border-2 border-brand-200 shrink-0">
                      <span className="text-2xl font-display font-bold text-brand-700">
                        {data.healthScore}
                      </span>
                      <span className="absolute -bottom-1 text-[9px] font-semibold text-brand-600 uppercase tracking-tight bg-white px-1.5 py-0.2 rounded-full border border-brand-200 shadow-2xs">
                        / 100
                      </span>
                    </div>
                    <div>
                      <div className="text-[11px] font-medium text-ink-faint uppercase tracking-wider">
                        Health Score
                      </div>
                      <span
                        className={`inline-block mt-1 px-2.5 py-0.5 rounded-full text-[11px] font-semibold border ${badge?.bg}`}
                      >
                        {badge?.label}
                      </span>
                    </div>
                  </div>

                  {/* Snapshot KPIs */}
                  <div className="md:col-span-3 grid grid-cols-3 gap-3">
                    <div className="p-3 rounded-xl bg-canvas border border-line/70">
                      <div className="text-[11px] font-medium text-ink-faint flex items-center gap-1">
                        <Users size={12} className="text-ink-soft" /> Headcount
                      </div>
                      <div className="text-base font-semibold text-ink mt-0.5">
                        {data.metricSnapshots.totalHeadcount}
                      </div>
                      <div className="text-[11px] text-ink-faint">
                        {data.metricSnapshots.attritionRatePercent}% turnover
                      </div>
                    </div>

                    <div className="p-3 rounded-xl bg-canvas border border-line/70">
                      <div className="text-[11px] font-medium text-ink-faint flex items-center gap-1">
                        <Clock size={12} className="text-ink-soft" /> Attendance
                      </div>
                      <div className="text-base font-semibold text-ink mt-0.5">
                        {data.metricSnapshots.attendanceRatePercent}%
                      </div>
                      <div className="text-[11px] text-emerald-600 font-medium">
                        Consistency
                      </div>
                    </div>

                    <div className="p-3 rounded-xl bg-canvas border border-line/70">
                      <div className="text-[11px] font-medium text-ink-faint flex items-center gap-1">
                        <TrendingUp size={12} className="text-ink-soft" /> Monthly Payroll
                      </div>
                      <div className="text-base font-semibold text-ink mt-0.5 truncate">
                        {formatCurrencyINR(data.metricSnapshots.monthlyPayrollCost)}
                      </div>
                      <div className="text-[11px] text-ink-faint">
                        Active commitment
                      </div>
                    </div>
                  </div>
                </div>
              </div>

              {/* Executive Summary Callout */}
              <div className="relative overflow-hidden rounded-2xl border border-brand-200/90 bg-gradient-to-r from-brand-50/90 via-purple-50/60 to-indigo-50/80 p-5 shadow-xs">
                <div className="flex items-start gap-3.5">
                  <div className="p-2.5 rounded-xl bg-brand-600 text-white shrink-0 mt-0.5 shadow-xs">
                    <Sparkles size={16} />
                  </div>
                  <div className="space-y-1">
                    <h4 className="text-[11px] font-bold uppercase tracking-wider text-brand-800">
                      Executive Summary
                    </h4>
                    <p className="text-[13.5px] font-medium text-ink leading-relaxed">
                      {data.executiveSummary || data.headline}
                    </p>
                  </div>
                </div>
              </div>

              {/* Key Highlights & Wins */}
              <div>
                <div className="flex items-center gap-2 text-xs font-bold uppercase tracking-wider text-emerald-800 mb-2.5">
                  <CheckCircle2 size={14} className="text-emerald-600" />
                  Key Highlights & Organizational Wins
                </div>
                <div className="grid grid-cols-1 md:grid-cols-2 gap-2.5">
                  {data.keyHighlights.map((highlight, idx) => (
                    <div
                      key={idx}
                      className="flex items-start gap-2.5 p-3.5 rounded-xl border border-emerald-200/80 bg-emerald-50/60 text-[12.5px] text-emerald-950 font-medium leading-snug shadow-2xs"
                    >
                      <span className="h-1.5 w-1.5 rounded-full bg-emerald-500 shrink-0 mt-1.5" />
                      <span>{highlight}</span>
                    </div>
                  ))}
                </div>
              </div>

              {/* Critical Concerns & Risk Areas */}
              <div>
                <div className="flex items-center gap-2 text-xs font-bold uppercase tracking-wider text-amber-800 mb-2.5">
                  <ShieldAlert size={14} className="text-amber-600" />
                  Critical Concerns & Risk Factors
                </div>
                <div className="space-y-2.5">
                  {data.criticalConcerns.map((concern, idx) => {
                    const isHigh = concern.severity === "HIGH";
                    const route = getConcernRoute(concern.area, concern.title);
                    const actionLabel = getActionLabel(concern.area, concern.title);
                    return (
                      <div
                        key={idx}
                        className={`p-3.5 rounded-xl border shadow-2xs transition-all ${
                          isHigh
                            ? "border-rose-200 bg-rose-50/60 text-rose-950 hover:border-rose-300"
                            : "border-amber-200 bg-amber-50/60 text-amber-950 hover:border-amber-300"
                        }`}
                      >
                        <div className="flex flex-wrap items-center justify-between gap-2 mb-1.5">
                          <div className="flex items-center gap-2 flex-wrap">
                            <span
                              className={`px-2 py-0.5 rounded text-[10px] font-bold uppercase tracking-wider ${
                                isHigh
                                  ? "bg-rose-600 text-white"
                                  : "bg-amber-600 text-white"
                              }`}
                            >
                              {concern.severity}
                            </span>
                            <span className="text-xs font-semibold">
                              {concern.title}
                            </span>
                            <span className="text-[11px] opacity-75">
                              · {concern.area}
                            </span>
                          </div>
                          <div className="flex items-center gap-2 shrink-0">
                            {concern.metric && (
                              <span className="text-[11px] font-semibold px-2 py-0.5 rounded-md bg-white border border-current opacity-80">
                                {concern.metric}
                              </span>
                            )}
                            {route && (
                              <button
                                type="button"
                                onClick={() => {
                                  onClose();
                                  navigate(route);
                                }}
                                className="inline-flex items-center gap-1 px-2.5 py-1 rounded-lg text-[11px] font-bold bg-white text-ink hover:bg-brand-50 hover:text-brand-700 border border-line hover:border-brand-300 shadow-2xs transition-all cursor-pointer"
                                title={`Navigate to ${actionLabel}`}
                              >
                                <span>{actionLabel}</span>
                                <ArrowUpRight size={13} className="text-brand-600" />
                              </button>
                            )}
                          </div>
                        </div>
                        <p className="text-[12px] opacity-90 leading-relaxed mt-1">
                          {concern.description}
                        </p>
                      </div>
                    );
                  })}
                </div>
              </div>

              {/* Strategic Action Items */}
              <div>
                <div className="flex items-center gap-2 text-xs font-bold uppercase tracking-wider text-brand-800 mb-2.5">
                  <Lightbulb size={14} className="text-brand-600" />
                  Strategic Leadership Recommendations
                </div>
                <div className="space-y-2.5">
                  {data.strategicRecommendations.map((rec, idx) => {
                    const recRoute = getRecommendationRoute(rec.category);
                    return (
                      <div
                        key={idx}
                        className="p-4 rounded-xl border border-line bg-white hover:border-brand-300 hover:shadow-xs transition shadow-2xs"
                      >
                        <div className="flex items-center justify-between gap-2 mb-1.5">
                          <div className="flex items-center gap-2">
                            <span className="flex items-center justify-center h-5 w-5 rounded-full bg-brand-100 text-brand-800 font-bold text-[11px]">
                              {idx + 1}
                            </span>
                            <span className="px-2 py-0.5 rounded text-[10px] font-semibold uppercase tracking-wider bg-canvas border border-line text-ink-soft">
                              {rec.category}
                            </span>
                            <span
                              className={`text-[10px] font-bold uppercase tracking-wider ${
                                rec.priority === "HIGH"
                                  ? "text-rose-600"
                                  : "text-amber-600"
                              }`}
                            >
                              {rec.priority} Priority
                            </span>
                          </div>
                          {recRoute && (
                            <button
                              type="button"
                              onClick={() => {
                                onClose();
                                navigate(recRoute);
                              }}
                              className="inline-flex items-center gap-1 text-[11px] font-semibold text-brand-600 hover:text-brand-800 hover:underline shrink-0 cursor-pointer"
                            >
                              <span>Take action</span>
                              <ArrowUpRight size={12} />
                            </button>
                          )}
                        </div>
                        <p className="text-[12.5px] font-medium text-ink leading-snug">
                          {rec.action}
                        </p>
                        <p className="text-[11.5px] text-ink-faint mt-1.5 flex items-center gap-1">
                          <span className="font-semibold text-ink-soft">
                            Expected Impact:
                          </span>{" "}
                          {rec.expectedImpact}
                        </p>
                      </div>
                    );
                  })}
                </div>
              </div>

              {/* Department Stability Pulse */}
              {data.departmentPulse && data.departmentPulse.length > 0 && (
                <div>
                  <h3 className="text-xs font-bold uppercase tracking-wider text-ink-faint mb-2">
                    Department Stability Pulse
                  </h3>
                  <div className="grid grid-cols-2 sm:grid-cols-3 md:grid-cols-5 gap-2">
                    {data.departmentPulse.map((dept, idx) => (
                      <div
                        key={idx}
                        className="p-3 rounded-xl border border-line bg-white text-center shadow-2xs"
                      >
                        <div className="flex items-center justify-center gap-1 text-[11.5px] font-semibold text-ink truncate">
                          <Building2 size={12} className="text-ink-faint" />
                          <span className="truncate">{dept.department}</span>
                        </div>
                        <div className="text-[10.5px] text-ink-faint mt-0.5">
                          {dept.headcount} staff
                        </div>
                        <span
                          className={`inline-block mt-1.5 px-2 py-0.5 rounded text-[10px] font-semibold ${
                            dept.health === "HEALTHY"
                              ? "bg-emerald-50 text-emerald-700 border border-emerald-200"
                              : dept.health === "WATCH"
                                ? "bg-amber-50 text-amber-700 border border-amber-200"
                                : "bg-blue-50 text-blue-700 border border-blue-200"
                          }`}
                        >
                          {dept.health}
                        </span>
                      </div>
                    ))}
                  </div>
                </div>
              )}
            </>
          )}
        </div>

        {/* Footer Actions */}
        <div className="flex items-center justify-between border-t border-line px-6 py-3.5 bg-white shrink-0">
          <div className="text-[11px] text-ink-faint flex items-center gap-1.5">
            <span>
              Engine:{" "}
              {data?.source === "llm"
                ? "AI Synthesized"
                : "Rule Intelligence"}
            </span>
          </div>
          <div className="flex items-center gap-2">
            <Button
              variant="outline"
              size="sm"
              onClick={handlePrint}
              className="gap-1.5 text-[12px]"
            >
              <Printer size={13} />
              Print / PDF
            </Button>
            <Button
              variant="outline"
              size="sm"
              onClick={handleCopyMarkdown}
              className="gap-1.5 text-[12px]"
            >
              {copied ? (
                <>
                  <Check size={13} className="text-emerald-600" />
                  Copied!
                </>
              ) : (
                <>
                  <Copy size={13} />
                  Copy Markdown
                </>
              )}
            </Button>
            <Button size="sm" onClick={onClose} className="text-[12px]">
              Done
            </Button>
          </div>
        </div>
      </div>
    </div>,
    document.body,
  );
}
